name: alugandoja
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

#####################
#-Requisitos Atuais-#
# MinSDK = 18       #
#####################

dependencies:
  cupertino_icons: ^1.0.2
  mocktail: any
  flutter_modular: any
  simple_animations: any
  dartz: 0.10.1
  dio: any
  bloc: 8.0.2
  bloc_test: 9.0.2
  alert_dialog: 1.0.0
  form_validation: 2.1.0+1
  static_translations: 2.1.0+1
  lottie:
  flutter_masked_text2:
  admob_flutter:
  firebase_core:
  firebase_analytics:

  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  assets:
    - assets/images/
    - assets/languages/
    - assets/animations/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
  uses-material-design: true
