// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3arlLyGNupwo4Xo9ZJj_dmja6xby0lIU',
    appId: '1:212971034148:android:0e84ef728c8cec8cb72ab1',
    messagingSenderId: '212971034148',
    projectId: 'alugandoja-3852b',
    storageBucket: 'alugandoja-3852b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArgmH0FHYOnPp6Sk24ZC7uEXa6uqHcYDA',
    appId: '1:212971034148:ios:094faf7a1d05625db72ab1',
    messagingSenderId: '212971034148',
    projectId: 'alugandoja-3852b',
    storageBucket: 'alugandoja-3852b.appspot.com',
    iosClientId: '212971034148-1pnguhp5u27otjhos1cg80t6cqujkitk.apps.googleusercontent.com',
    iosBundleId: 'com.alugandoja',
  );
}
